<?php

 /**
  * @var \Magento\Framework\Escaper $escaper
  */
?>
<div class="search-main block block-search">
    <input type="text" 
           placeholder="<?= $escaper->escapeHtmlAttr(__('search here...')) ?>" 
           id="searchbox" class="searchbox" />
    <div id="search-component" data-bind="scope:'searchcomponent'">
        <!-- ko template: getTemplate() --><!-- /ko -->
        <script type="text/x-magento-init">
        {
            "#search-component": {
                "Magento_Ui/js/core/app": {
                "components": {
                        "searchcomponent": {
                            "component": "Conversionbox_Predictivesearch/js/searchAutocomplete"
                        }
                    }
                }
            }
        }
        </script>
    </div>
<div class="actions"><button type="submit" title="Search" class="action search" disabled=""><span>Search</span></button></div>
</div>
<script>
document.querySelector('.action.search').addEventListener('click', function(e) {
    e.preventDefault();
    let keyword = document.getElementById('searchbox').value.trim();
    if (keyword) {
        window.location.href = '/catalogsearch/result/?q=' + encodeURIComponent(keyword);
    }
});
</script>
